add_newline = true

# [character]
# success_symbol = "[ï¬¦](bold green)"
# error_symbol = "[ï¬¦](bold red)"

[package]
symbol = "ï£” "

[nodejs]
symbol = "ïŸ— "

[git_branch]
symbol = "ðŸŒ± "
# symbol= "îœ¥ "

[golang]
symbol = "ï³‘ "

[aws]
format = ''
